# Generated by Django 5.2.5 on 2025-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Payment Failed', 'Payment Failed')], default='Processing', max_length=50),
        ),
    ]
