# Generated by Django 5.2.5 on 2025-09-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='item_subtotal',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_variant',
            new_name='variant',
        ),
    ]
