import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { UserProvider } from "@/app/userContext";
import { jwtDecode } from "jwt-decode";
import { MyJwtPayload } from "@/types";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let user_id = "";
  let is_admin = false;

  const refreshToken = (await cookies()).get("session_refresh_token")?.value
  
  if (refreshToken) {
    user_id = jwtDecode<MyJwtPayload>(refreshToken).user_id
    is_admin = jwtDecode<MyJwtPayload>(refreshToken).is_admin
  };



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider userInfo ={{ user_id, is_admin }}>
          <Navbar key={user_id} />      
          {children}
        </UserProvider>
        
        <Footer />
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
