# Generated by Django 5.2.5 on 2025-09-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='is_admin',
        ),
    ]
